- name: Instance and r53 rescords creation
  hosts: all 
  connection: ssh
  vars:
    sg_id: sg-07afeb4dfbab74912
    ami_id: ami-0220d79f3f480ecf5
    env: Dev
    action: create
    domain_name: 100pushups.online
    instances:
      - "mongodb"
      - "catalogue"
  tasks: 
    - name: Instance creation
      ansible.builtin.debug:
        msg: "Creating the instances"
      
    - name: Instance
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: "{{ami_id}}"
        security_group: "{{sg_id}}"
        name: "{{item}}-{{env}}"
        tags: 
          Environment: "{{env}}" 
          Project: Roboshop
          Component: "{{item}}"
          Name: "{{item}}-{{env}}"   
      loop: "{{instances}}" 
      register: ec2_output
      when: action == "create"

    - name: Printing ec2_output
      ansible.builtin.debug:
        msg: "{{ec2_output}}"

    - name: Create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{domain_name}}"
        record: "{{item.item}}-{{env}}.{{domain_name}}"
        value: "{{item}}.instances[0].private_ip_address}}"
        ttl: 1
        type: A
        overwrite: true
        wait: false
      loop: "{{ec2_output.results}}"
      when: action == "create"

    - name: Create r53 records for frontend
      amazon.aws.route53:
        state: present
        zone: "{{domain_name}}"
        record: "roboshop-{{env}}.{{domain_name}}"
        value: "{{item.instances[0].public_ip_address}}"
        ttl: 1
        type: A
        overwrite: true
        wait: false
      loop: "{{ec2_output.results}}"
      when: 
      - action == "create"
      - item.item == "frontend"




  


