- name: Creating instances
  hosts: all
  connection: ssh
  vars:
    instance:
      - "mongodb"
      - "catalogue"
    env: dev
    sg_id: sg-07afeb4dfbab74912
    frontend_sg_id: sg-062dd749ba63aac5e
    ami_id: ami-0220d79f3f480ecf5
    action: create
    hosted_zone: 100pushups.online
  tasks:
    - name: Instance
      ansible.builtin.debug:
        msg: "Creating {{item}}"
      loop: "{{instance}}"

    - name: selecting sg_id based on server
      ansible.builtin.set_fact:
        sg: "{{frontend_sg_id}}"
      when: item=="frontend"
      loop: "{{instance}}"

    - name: selecting sg_id based on server 1
      ansible.builtin.set_fact:
        sg: "{{sg_id}}"
      when: item != "frontend"
      loop: "{{instance}}"

    - name: Instance creation
      amazon.aws.ec2_instance:
        name: "{{item}}-{{env}}"
        security_group: "{{sg}}"
        image_id: "{{ami_id}}"
        instance_type: t3.micro
        tags:
          Environment: "{{env}}"
          Project: Roboshop
          user: system
        wait: true
      loop: "{{instance}}"
      register: ec2_output
      when: action == "create"

    - name: Print ec2_output
      ansible.builtin.debug:
        msg: "{{ec2_output}}"

    - name: Creating R53 records
      amazon.aws.route53:
        state: present
        zone: "{{hosted_zone}}"
        record: "{{item.item}}-{{env}}.{{hosted_zone}}"
        value: "{{item.instances[0].private_ip_address}}"
        ttl: 1
        type: A
        overwrite: true
        wait: false
      loop: "{{ec2_output.results}}"
      when: action=="create"

      register: r53_output

    - name: output of r53 records
      ansible.builtin.debug:
        msg: "{{r53_output}}"

    - name: Creating R53 records
      amazon.aws.route53:
        state: present
        zone: "{{hosted_zone}}"
        record: "{{item.item}}-{{env}}.{{hosted_zone}}"
        value: "{{item.instances[0].public_ip_address}}"
        ttl: 1
        type: A
        overwrite: true
        wait: false
      loop: "{{ec2_output.results}}"
      when: 
      - action=="create"
      - item.item==frontend
      register: r53_output

    - name: output of r53 records
      ansible.builtin.debug:
        msg: "{{r53_output}}"

